services:
  app:
    image: ghcr.io/xyqyear/sub-manager
    # build: .
    ports:
      - "5678:5678"
    volumes:
      - ./data:/app/backend/data
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN:?set ADMIN_TOKEN}
      - DATABASE_URL=sqlite+aiosqlite:///./data/db.sqlite3
    restart: unless-stopped
